In [1]:
import numpy as np

In [3]:
# Scenario - 1

a1 = np.arange(8).reshape(2,4)
a2 = np.arange(8,16).reshape(2,4)

print(a1)
print(a2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [4]:
a1 + a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [6]:
# Scenario - 2

a3 = np.arange(9).reshape(3,3)
a4 = np.arange(3).reshape(1,3)

print(a3, a4)

[[0 1 2]
 [3 4 5]
 [6 7 8]] [[0 1 2]]


In [7]:
a3+a4

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

Broadcasting in NumPy arrays is a powerful feature that allows arrays of different shapes to be used together in arithmetic operations. It eliminates the need for explicit looping over array elements and provides a more concise and efficient way to perform calculations.

In NumPy, arrays are required to have the same shape in order to perform element-wise operations. However, broadcasting relaxes this constraint by automatically aligning arrays with different shapes to make the operations compatible.

## Rules for Broadcasting

In [9]:
# If x=1 and y=n then also operation will take place(same dimension)
a5 = np.arange(3).reshape(1,3)
a6 = np.arange(12).reshape(4,3)

print(a5)
print()
print(a6)

[[0 1 2]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [10]:
a5+a6

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [13]:
# If x=1 and y!=n then also operation will not take place

a7 = np.arange(3).reshape(1,3)
a8 = np.arange(16).reshape(4,4)

In [14]:
# If x=1 and n=1 and y==m, operation to take place

a11 = np.arange(3).reshape(1,3)
a12 = np.arange(3).reshape(3,1)

print(a11)
print()
print(a12)

[[0 1 2]]

[[0]
 [1]
 [2]]


In [15]:
# If x=1 and y=1, then the operation will take place no matter what

a13 = np.arange(1).reshape(1,1)
a14 = np.arange(20).reshape(4,5)

print(a13)
print()
print(a14)

[[0]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [17]:
a13 + a14

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [16]:
# If they are from different dimensions

a15 = np.arange(4)
a16 = np.arange(20).reshape(5,4)

print(a15)
print()
print(a16)

[0 1 2 3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [18]:
a15+a16

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18],
       [16, 18, 20, 22]])