Ways to create Numpy arrays:-

1. Using np.array()/1-D and 2-D
2. Using np.zeros/ones/empty/random()
3. Using np.arange()
4. Using np.linspace()
5. Using Copy()
6. Using Identity()

In [1]:
import numpy as np

In [3]:
# 1-D array / vector
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
# 2-D array / matrix
arr2 = np.array([[1,2,3], [4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr3 = np.zeros((2,3)) # 2 rows and 3 coloumns
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
arr4 = np.ones((3,4)) # 3 rows and 4 coloumns
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
arr5 = np.identity(5) # 5x5 array
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
arr6 = np.arange(10)
print(arr6)
arr7 = np.arange(3,20,4)
print(arr7)

[0 1 2 3 4 5 6 7 8 9]
[ 3  7 11 15 19]


In [13]:
arr8 = np.linspace(10,20,10)
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [14]:
arr9 = arr8.copy()
arr9

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])