In [1]:
import numpy as np

In [2]:
np.random.random()

0.9775554106077189

In [4]:
np.random.seed(1) # Same random value again and again
np.random.random()

0.417022004702574

In [11]:
np.random.uniform(3,10) #random value from 3 to 10

5.418925089301334

In [12]:
np.random.uniform(1,100,10) #10 random values from 1 to 100

array([40.27997995, 54.34285667, 42.50025693, 68.83673054, 21.24077272,
       87.9336262 ,  3.71137173, 67.37628351, 42.31317543, 56.31029302])

In [13]:
np.random.uniform(1,100,10).reshape(2,5)

array([[14.89830692, 20.61204742, 80.2737123 , 96.857896  , 32.02899364],
       [69.53993895, 87.76252608, 89.56605969,  9.41937693,  4.86642354]])

In [26]:
np.random.randint(1,100)

44

In [28]:
np.random.randint(1,100,15).reshape(3,5)

array([[83, 16, 65, 69, 26],
       [99, 88,  8, 27, 26],
       [23, 10, 68, 24, 28]])

In [30]:
a = np.random.randint(1,10,6)

In [31]:
a

array([6, 4, 7, 9, 1, 3])

In [32]:
a.max()

9

In [33]:
a.min()

1

In [34]:
np.argmax(a) # index of max element

3

In [35]:
np.argmin(a) #index of min element

4

In [48]:
a = np.random.randint(1,100,6)
a

array([78,  7, 53, 86, 71,  3])

In [49]:
a[a%2==1] = -1 # inplace operation
a

array([78, -1, -1, 86, -1, -1])

In [51]:
# not inplace operation
# where(condition,True,False)
a = np.random.randint(1,100,6)
a

array([77, 92, 22, 76,  8, 78])

In [54]:
b = np.where(a%2==1,-1,a) # not in place
b

array([-1, 92, 22, 76,  8, 78])

In [53]:
a # original array

array([77, 92, 22, 76,  8, 78])

In [55]:
a = np.random.randint(1,100,10)
a

array([73, 76, 77, 44, 21, 31, 37,  8, 46, 69])

In [57]:
a = np.sort(a)
a

array([ 8, 21, 31, 37, 44, 46, 69, 73, 76, 77])

In [59]:
# Percentile
np.percentile(a,45)

44.1

In [60]:
np.percentile(a,50)

45.0

In [61]:
np.percentile(a,100)

77.0

In [62]:
np.percentile(a,99.8)

76.982