In [1]:
import numpy as np

In [2]:
arr = np.random.randint(low=1, high=100, size=20).reshape(4,5)
arr

array([[74, 32, 27, 97, 36],
       [88, 72, 73, 12, 80],
       [13, 94, 86, 87, 76],
       [ 8, 98, 74, 22, 71]])

In [3]:
arr>50

array([[ True, False, False,  True, False],
       [ True,  True,  True, False,  True],
       [False,  True,  True,  True,  True],
       [False,  True,  True, False,  True]])

In [4]:
(arr>50).shape

(4, 5)

### Indexing/Filtering using Boolean arrays

In [5]:
arr[arr>50]

array([74, 97, 88, 72, 73, 80, 94, 86, 87, 76, 98, 74, 71])

In [6]:
arr[(arr>50) & (arr%2!=0)]

array([97, 73, 87, 71])

In [7]:
arr[(arr>50) & (arr%2!=0)] = 0
arr

array([[74, 32, 27,  0, 36],
       [88, 72,  0, 12, 80],
       [13, 94, 86,  0, 76],
       [ 8, 98, 74, 22,  0]])