In [1]:
import numpy as np

In [2]:
arr = np.arange(24)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [3]:
arr1 = np.arange(24).reshape(6,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [7]:
arr1[2]

array([ 8,  9, 10, 11])

In [8]:
arr1[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [9]:
arr1[2:4, 1:3]

array([[ 9, 10],
       [13, 14]])

In [11]:
arr1[4:,2:]

array([[18, 19],
       [22, 23]])

In [12]:
for i in arr1:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [14]:
for i in np.nditer(arr1):
    print(i, end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 