In [1]:
import numpy as np

Reshaping Numpy arrays:-

1. Ravel
2. Reshape
3. Transpose
4. Stacking
5. Splitting

In [2]:
arr1 = np.arange(6,12).reshape(3,2)
arr1

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [4]:
arr1.ndim

2

In [3]:
arr1.ravel() # converts to 1D array

array([ 6,  7,  8,  9, 10, 11])

In [6]:
arr1.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [7]:
arr2 = np.array([[0,1,2],[3,4,5]])
arr2

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
arr3 = np.arange(12,18).reshape(2,3)
arr3

array([[12, 13, 14],
       [15, 16, 17]])

In [9]:
np.hstack((arr3,arr2))

array([[12, 13, 14,  0,  1,  2],
       [15, 16, 17,  3,  4,  5]])

In [10]:
np.vstack((arr2,arr3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [11]:
np.hsplit(arr3,3)

[array([[12],
        [15]]),
 array([[13],
        [16]]),
 array([[14],
        [17]])]

In [12]:
np.vsplit(arr3,2)

[array([[12, 13, 14]]), array([[15, 16, 17]])]