Properties and Attributes:-

1. shape
2. ndim
3. size
4. itemsize
5. dtype
6. astype()

In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [5]:
arr1.shape

(5,)

In [6]:
arr2 = np.array([[1,2,3,4], [5,6,7,8]])
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr2.shape

(2, 4)

In [8]:
arr2.ndim #2D matrix

2

In [10]:
arr3 = np.array([[[1,2], [3,4]], [[5,6],[7,8]]])
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [11]:
arr3.ndim # no () after ndim because it is an attribute not a method

3

In [12]:
arr3.size # number of items

8

In [13]:
arr2.itemsize # size of memory occupied

4

In [14]:
arr4 = np.linspace(10,20,10)
arr4

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [15]:
arr4.itemsize

8

In [16]:
arr4.dtype

dtype('float64')

In [17]:
arr2.dtype

dtype('int32')

In [18]:
arr3.dtype

dtype('int32')

In [19]:
arr3.astype('float') # changes the datatype

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [20]:
arr4.astype('int') # won't make changes to the original object

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 20])

astype() -> it is generally used in ML when converting the dataype of a feature from say 'float' to 'int', it decreases the memory consumed as well as provide absolute values in our taken case like Age.

In [21]:
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [22]:
arr4

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])